NODE=$(uname -n)

case $NODE in
    penguin)
        IP=$(hostname -I)
        alias jsrv="bundle exec jekyll serve --host $IP"
        alias hsrv="hugo server --bind $IP --baseURL http://$IP/ --appendPort"
        ;;
    arch2-vb)
        IP=$(hostname -i)
        alias jsrv="bundle exec jekyll serve --host ${IP}"
        alias hsrv="hugo server --bind ${IP} --baseURL http://${IP}/ --appendPort"
        ;;
    *)
        alias jsrv="bundle exec jekyll serve"
        alias hsrv="hugo server"
        ;;
esac

mkpost() {
   hugo new --editor vim post/$1.md
}

if [[ -x ~/.bashrc_local_aliases ]]; then
    . ~/.bashrc_local_aliases
fi
