"set verbosefile=verbose.txt
let mapleader = ","

" color {{{1
if ! has('gui_running')
    " if we're not running the gui
    " try to set up for true color support
    set termguicolors
    let &t_Co=256
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" Set the color scheme
colorscheme neutron

" Global config options {{{1
"Tab Stop handling
set tabstop=4 softtabstop=4 expandtab shiftwidth=4 smarttab shiftround

" line numbering is on. don't use relative line numbers,
" use 5 columns for line numbers
set number norelativenumber numberwidth=5

" Allow buffers to be open and windowless, even if changed.
set hidden

"Turn off the mouse
set mouse=

" Let the plugins highlight, etc
syntax on
filetype plugin indent on

" Automatically change directory to
" be that of the current buffer.
"set autochdir

set laststatus=2

"End global config options }}}1

" File_type autocmd groups {{{1
" Markdown
" textwrapping
" Placed in an auto command group to allow
" no dups when re loading vimrc.
" c.f. http://learnvimscriptthehardway.stevelosh.com/chapters/14.html
"
augroup filetype_md
    autocmd!
    autocmd FileType markdown setlocal textwidth=79 formatoptions+=t autoindent
    autocmd FileType markdown setlocal listchars=eol:$,tab:>·,trail:~
augroup END

" Vim
" Set folding on markers
"
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END
" End File_type groups }}}1


" Allow status lines to be selected or hidden (show by default)
"let s:hidden_all = 0
"function! ToggleHiddenAll()
"    if s:hidden_all  == 0
"        let s:hidden_all = 1
"        set noshowmode
"        set noruler
"        set laststatus=0
"        set noshowcmd
"    else
"        let s:hidden_all = 0
"        set showmode
"        set ruler
"        set laststatus=2
"        set showcmd
"    endif
"endfunction
"
"nnoremap <leader>hide :call ToggleHiddenAll()<CR>
"
"" Be sure these match the ones above
"set showmode
"set ruler
"set laststatus=2
"set showcmd

" Key bindings {{{1

" Toggle paste mode
nnoremap <leader>pp :set paste!<CR>

" Disable the arrow keys in normal mode.
" I really need to learn to move efficiently.
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>

" Move the current line down in the file
"noremap - ddp
" Move the current line up in the file
"noremap _ ddkP

" Make it easy to edit .vimrc
noremap <leader>vim :tabnew $MYVIMRC<cr>
noremap <leader>sv :source $MYVIMRC<cr>

" NERDTree support
" Note that the suggested <C-o> hides the
" jump list commands which are way more useful
" than NERDTree
map <leader>nt :NERDTreeToggle<CR>

" Buffer navigation
noremap <C-n> :bn<CR>
noremap <C-p> :bp<CR>

" Move to the next buffer and close the one we started on.
nnoremap <C-w>d :bn<CR>:bd#<CR>

" Fancy version of the above
nnoremap <C-w>! <Plug>Kwbd

" Toggle line numbers
nnoremap <leader>nn :set number!<cr>

" window nav
" from: https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally 
nnoremap <C-j> <C-W><C-J>
nnoremap <C-k> <C-W><C-K>
nnoremap <C-l> <C-W><C-L>
nnoremap <C-h> <C-W><C-H>

" Tab Nav
" Alt-n => next tab
" Alt-p => previous tab
if has('gui_running')
    nnoremap ð <C-PageUp>
    nnoremap î <c-PageDown>
else
    nnoremap p <C-PageUp>
    nnoremap n <c-PageDown>
endif

" plugin config {{{1

" lightline config
let g:lightline = {
   \ 'colorscheme' : 'solarized'
   \ }
" lightline shows this for us
set noshowmode

" Project support {{{1
if $PVIM_PROJECT_FILE != '' 
    source $PVIM_PROJECT_FILE
endif
